language: java
jdk:
    - openjdk8
before_script:
    - echo "MAVEN_OPTS='-Xmx1g'" > ~/.mavenrc
    - git clone https://github.com/doudouchat/exemple-service.git /tmp/exemple-service
    - mvn -f /tmp/exemple-service clean install -Dmaven.test.skip=true
script: mvn -s .travis.settings.xml verify -Pauthorization,it
after_success:
    - bash <(curl -s https://codecov.io/bash)
install: true
sudo: false
cache:
    directories:
        - $HOME/.m2
        - $HOME/.embedded-cassandra