language: java
jdk:
    - openjdk8
script: mvn -s .travis.settings.xml verify -e
after_success:
    - bash <(curl -s https://codecov.io/bash)
install: true
sudo: false
cache:
    directories:
        - $HOME/.m2