authorization:
   resource:
      cassandra:
         resource_configuration: file:/usr/local/tomcat/etc/cassandra.conf
   zookeeper:
      host: 172.17.0.1:10024
   certificat:
      location: file:/usr/local/tomcat/etc/mytest.jks
      alias: mytest
      password: mypass
   kafka:
      bootstrap-servers: localhost:10025
   hazelcast:
      addresses: 172.17.0.1:5706
      cluster: dev
application:
   zookeeper:
      host: 172.17.0.1:10024