authorization:
   resource:
      cassandra:
         resource_configuration: file:/usr/local/tomcat/etc/cassandra.conf
   hazelcast:
      port: 5705
      member: 127.0.0.1:5705
   zookeeper:
      host: 172.17.0.1:10024
   certificat:
      location: file:/usr/local/tomcat/etc/mytest.jks
      alias: mytest
      password: mypass
   kafka:
      bootstrap-servers: localhost:10025
application:
   zookeeper:
      host: 172.17.0.1:10024